package ru.shprot.sudokumobdevkz.core.base.domain.model

import androidx.compose.ui.graphics.Color
import kotlinx.serialization.Serializable
import ru.shprot.sudokumobdevkz.core.theme.AppColors

@Serializable
data class ThemeColors(
    val primary: Long,
    val primaryDark: Long,
    val primaryLight: Long,
    val secondary: Long,
    val background: Long,
    val backgroundCard: Long,
    val backgroundCardAccent: Long,
    val surface: Long,
    val text: Long,
    val textSecondary: Long,
    val textOnPrimary: Long,
    val textAccent: Long,
    val error: Long,
    val errorLight: Long,
    val success: Long,
    val warning: Long,
    val gridLine: Long,
    val gridLineBold: Long,
    val cellSelected: Long,
    val cellHighlight: Long,
    val cellSameNumber: Long,
    val cellError: Long,
    val cellFixed: Long,
    val cellEditable: Long,
    val draftText: Long,
    val divider: Long,
    val iconTint: Long,
    val bottomNavSelected: Long,
    val bottomNavUnselected: Long,
    val chipSelected: Long,
    val chipUnselected: Long,
    val chipTextSelected: Long,
    val chipTextUnselected: Long,
    val progressTrack: Long,
    val progressIndicator: Long,
    val barChart: Long,
    val barChartLabel: Long,
)

fun ThemeColors.toAppColors(): AppColors = AppColors(
    primary = Color(primary),
    primaryDark = Color(primaryDark),
    primaryLight = Color(primaryLight),
    secondary = Color(secondary),
    background = Color(background),
    backgroundCard = Color(backgroundCard),
    backgroundCardAccent = Color(backgroundCardAccent),
    surface = Color(surface),
    text = Color(text),
    textSecondary = Color(textSecondary),
    textOnPrimary = Color(textOnPrimary),
    textAccent = Color(textAccent),
    error = Color(error),
    errorLight = Color(errorLight),
    success = Color(success),
    warning = Color(warning),
    gridLine = Color(gridLine),
    gridLineBold = Color(gridLineBold),
    cellSelected = Color(cellSelected),
    cellHighlight = Color(cellHighlight),
    cellSameNumber = Color(cellSameNumber),
    cellError = Color(cellError),
    cellFixed = Color(cellFixed),
    cellEditable = Color(cellEditable),
    draftText = Color(draftText),
    divider = Color(divider),
    iconTint = Color(iconTint),
    bottomNavSelected = Color(bottomNavSelected),
    bottomNavUnselected = Color(bottomNavUnselected),
    chipSelected = Color(chipSelected),
    chipUnselected = Color(chipUnselected),
    chipTextSelected = Color(chipTextSelected),
    chipTextUnselected = Color(chipTextUnselected),
    progressTrack = Color(progressTrack),
    progressIndicator = Color(progressIndicator),
    barChart = Color(barChart),
    barChartLabel = Color(barChartLabel),
)