plugins {
    id 'com.android.application'
}

def localProperties = new Properties()
def localPropertiesFile = rootProject.file('local.properties')
if (localPropertiesFile.exists()) {
    localProperties.load(new FileInputStream(localPropertiesFile))
}

android {
    compileSdk 36

    defaultConfig {
        applicationId "ru.shprot.sudokumobdevkz"
        minSdk 24
        targetSdk 36
        versionCode 8
        versionName "1.1.0"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    signingConfigs {
        release {
            storeFile file(localProperties.getProperty('KEYSTORE_FILE', System.getenv('KEYSTORE_FILE') ?: 'keystore.jks'))
            storePassword localProperties.getProperty('KEYSTORE_PASS', System.getenv('KEYSTORE_PASS') ?: '')
            keyAlias localProperties.getProperty('KEYSTORE_ALIAS', System.getenv('KEYSTORE_ALIAS') ?: '')
            keyPassword localProperties.getProperty('KEYSTORE_ALIAS_PASS', System.getenv('KEYSTORE_ALIAS_PASS') ?: '')
        }
    }

    buildTypes {
        debug {
            debuggable true
            minifyEnabled false
        }
        release {
            signingConfig signingConfigs.release
            debuggable false
            minifyEnabled true
            shrinkResources true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    buildFeatures {
        viewBinding true
    }
    namespace 'ru.shprot.sudokumobdevkz'
}

dependencies {

    implementation 'androidx.appcompat:appcompat:1.7.1'
    implementation 'com.google.android.material:material:1.13.0'
    implementation 'androidx.constraintlayout:constraintlayout:2.2.1'
    testImplementation 'junit:junit:4.13.2'
    androidTestImplementation 'androidx.test.ext:junit:1.3.0'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.7.0'

    def nav_version = "2.9.7"

    // Java language implementation
    implementation "androidx.navigation:navigation-fragment:$nav_version"
    implementation "androidx.navigation:navigation-ui:$nav_version"

    def room_version = "2.8.4"

    implementation "androidx.room:room-runtime:$room_version"
    annotationProcessor "androidx.room:room-compiler:$room_version"

    implementation 'io.reactivex.rxjava2:rxjava:2.2.21'
    implementation 'io.reactivex.rxjava2:rxandroid:2.1.1'
    implementation "androidx.room:room-rxjava2:$room_version"

    implementation 'com.github.fornewid:neumorphism:0.3.2'

    implementation 'com.intuit.ssp:ssp-android:1.1.1'
    implementation 'com.intuit.sdp:sdp-android:1.1.1'

    implementation 'com.google.android.play:review:2.0.2'
}
