package ru.shprot.sudokumobdevkz.core.theme

import androidx.compose.runtime.staticCompositionLocalOf
import androidx.compose.ui.graphics.Color

data class AppColors(
    val primary: Color,
    val primaryDark: Color,
    val primaryLight: Color,
    val secondary: Color,
    val background: Color,
    val backgroundCard: Color,
    val backgroundCardAccent: Color,
    val surface: Color,
    val text: Color,
    val textSecondary: Color,
    val textOnPrimary: Color,
    val textAccent: Color,
    val error: Color,
    val errorLight: Color,
    val success: Color,
    val warning: Color,
    val gridLine: Color,
    val gridLineBold: Color,
    val cellSelected: Color,
    val cellHighlight: Color,
    val cellSameNumber: Color,
    val cellError: Color,
    val cellFixed: Color,
    val cellEditable: Color,
    val draftText: Color,
    val divider: Color,
    val iconTint: Color,
    val bottomNavSelected: Color,
    val bottomNavUnselected: Color,
    val chipSelected: Color,
    val chipUnselected: Color,
    val chipTextSelected: Color,
    val chipTextUnselected: Color,
    val progressTrack: Color,
    val progressIndicator: Color,
    val barChart: Color,
    val barChartLabel: Color,
) {
    companion object {
        val LightColors = AppColors(
            primary = Color(0xFF34C759),
            primaryDark = Color(0xFF2DA44E),
            primaryLight = Color(0xFFE8F8ED),
            secondary = Color(0xFFF5F5F5),
            background = Color(0xFFF8F9FA),
            backgroundCard = Color(0xFFFFFFFF),
            backgroundCardAccent = Color(0xFFFFF9E6),
            surface = Color(0xFFFFFFFF),
            text = Color(0xFF1A1A1A),
            textSecondary = Color(0xFF8E8E93),
            textOnPrimary = Color(0xFFFFFFFF),
            textAccent = Color(0xFF34C759),
            error = Color(0xFFFF3B30),
            errorLight = Color(0xFFFFE5E3),
            success = Color(0xFF34C759),
            warning = Color(0xFFFF9500),
            gridLine = Color(0xFF96B391),
            gridLineBold = Color(0xFF546E7A),
            cellSelected = Color(0xFFB6DAB3),
            cellHighlight = Color(0xFFD6EBD2),
            cellSameNumber = Color(0xFFC0E1BB),
            cellError = Color(0xFFFF3B30).copy(alpha = 0.15f),
            cellFixed = Color(0xFF546E7A),
            cellEditable = Color(0xFF70856D),
            draftText = Color(0xFF868991),
            divider = Color(0xFFE5E5EA),
            iconTint = Color(0xFF636366),
            bottomNavSelected = Color(0xFF34C759),
            bottomNavUnselected = Color(0xFFC7C7CC),
            chipSelected = Color(0xFF34C759),
            chipUnselected = Color(0xFFF2F2F7),
            chipTextSelected = Color(0xFFFFFFFF),
            chipTextUnselected = Color(0xFF636366),
            progressTrack = Color(0xFFE5E5EA),
            progressIndicator = Color(0xFF34C759),
            barChart = Color(0xFF34C759),
            barChartLabel = Color(0xFF8E8E93),
        )

        val DarkColors = AppColors(
            primary = Color(0xFF30D158),
            primaryDark = Color(0xFF28A745),
            primaryLight = Color(0xFF1B3A26),
            secondary = Color(0xFF2C2C2E),
            background = Color(0xFF1C1C1E),
            backgroundCard = Color(0xFF2C2C2E),
            backgroundCardAccent = Color(0xFF3A3A3C),
            surface = Color(0xFF2C2C2E),
            text = Color(0xFFFFFFFF),
            textSecondary = Color(0xFF8E8E93),
            textOnPrimary = Color(0xFFFFFFFF),
            textAccent = Color(0xFF30D158),
            error = Color(0xFFFF453A),
            errorLight = Color(0xFF3A1A18),
            success = Color(0xFF30D158),
            warning = Color(0xFFFF9F0A),
            gridLine = Color(0xFF58585A),
            gridLineBold = Color(0xFFD0D0D0),
            cellSelected = Color(0xFF30D158).copy(alpha = 0.40f),
            cellHighlight = Color(0xFF30D158).copy(alpha = 0.18f),
            cellSameNumber = Color(0xFF30D158).copy(alpha = 0.28f),
            cellError = Color(0xFFFF453A).copy(alpha = 0.25f),
            cellFixed = Color(0xFFE5E5E7),
            cellEditable = Color(0xFF5AC87A),
            draftText = Color(0xFF9E9EA3),
            divider = Color(0xFF48484A),
            iconTint = Color(0xFF8E8E93),
            bottomNavSelected = Color(0xFF30D158),
            bottomNavUnselected = Color(0xFF636366),
            chipSelected = Color(0xFF30D158),
            chipUnselected = Color(0xFF3A3A3C),
            chipTextSelected = Color(0xFFFFFFFF),
            chipTextUnselected = Color(0xFF8E8E93),
            progressTrack = Color(0xFF48484A),
            progressIndicator = Color(0xFF30D158),
            barChart = Color(0xFF30D158),
            barChartLabel = Color(0xFF8E8E93),
        )
    }
}

internal val LocalAppColors = staticCompositionLocalOf {
    AppColors.LightColors
}
